safe:   false
port:   4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

blog:
  title: are you evolving?
  url: http://toevolve.org
  copyright: Copyright (c) 2010 Vincent Landgraf
  author: Vincent Landgraf
  email: vilandgr+toevolve@googlemail.org
  language: en_EN
  keywords: ruby blog
  description: a blog from vincent landgraf
  disqus: toevolve

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

